npm install --save-dev asar
npm install --save-dev electron-packager
npm install --save-dev electron-prebuilt
npm install --save-dev fs-jetpack
npm install --save-dev gulp
npm install --save-dev gulp-less
npm install --save-dev gulp-util
npm install --save-dev q
npm install --save-dev rollup
npm install --save-dev tree-kill
npm install --save-dev yargs